### ISSUE TITLE
[Improvement] Add tests.

### ISSUE THREAD

**Issue by pandevim** [YouTubeNLP/Backend#18]
There are no tests for the code at the moment. This has led to manual testing on new feature.
1. Need local development test for developers.
2. Need automatic test executing using github actions trigger on each PR and automatic result generation.

All services should receive some kind of unit test.
The skeleton of the `test/` directory in root can be:
```
tests/
  unit/ # for all services
  integration/ # for integration with NLP and Frontend repo
```
This may include working with different teams, setting up a test python package, setting up linter, etc.

**Comment by karkipra** [comment]
Any ideas of what libraries to use for tests? Since we'll be starting with unit tests, maybe `unittest` and some form of mocking? Something like this might be good starting point: https://stackoverflow.com/questions/15753390/how-can-i-mock-requests-and-the-response. As for integration, linter, CI pipeline - that's gonna need more thinking.

**Comment by edward2018211** [comment]
Yea I think ```unittest``` is a good start. For linter, we could use something like https://github.com/marketplace/actions/python-linting through GitHub Actions for basic enforcement of good Python practice. Anyone have suggestions/recommendations for integration and CI pipeline?

**Comment by pandevim** [comment]
At the moment I only know about `pytest` package for testing. @karkipra yes I think it would be a good idea to use mocking. @edward2018211 that github action looks sleek but for now I think we can put the automation part to backlog and first setup the local test environment.
